server:
   port: 8090

spring:
  datasource:    url: jdbc:mysql://localhost:3306/cbtransfer?serverTimezone=GMT%2B8
    username: wangsai
    password: wangsai123
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:  mapper-locations:  - classpath:mapping/*.xml
  type-aliases-package: com.wangxiao.model     
  